// Embed the compiled .wasm as base64 so the content script bundle is
// self-contained — no runtime fetch and no web_accessible_resources, which
// content scripts cannot rely on. Regenerated by `bun run wasm`; the output
// lives under src/wasm/generated/ and is gitignored.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const dir = resolve(here, '../src/wasm/generated')
const wasm = readFileSync(resolve(dir, 'matcher_bg.wasm'))
const base64 = wasm.toString('base64')

const out = `// AUTO-GENERATED by scripts/inline-wasm.ts — do not edit.
// Base64-embedded wasm-matcher binary for self-contained content scripts.
const BASE64 =
  '${base64}'

function decode(b64: string): Uint8Array {
  const binary = atob(b64)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i)
  }
  return bytes
}

export const wasmBytes: Uint8Array = decode(BASE64)
`

writeFileSync(resolve(dir, 'matcher-inline.ts'), out)
console.log(
  `>> inlined ${wasm.length} bytes -> src/wasm/generated/matcher-inline.ts`,
)
